name: Generate Snake Animation

on:
  schedule: # Run the job at 02:00 UTC every day
    - cron: "0 2 * * *"
  push: # Run the job on every push to the main branch
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: KillerAG99
          outputs: dist/snake.svg

      - name: Push the animation to the repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          commit_message: "Generate snake animation"
          files: dist/snake.svg
